language: node_js
cache: npm

services:
  - docker

script:
  - pushd src
  - zip -r sourceforts-server-build-notification-handler.zip notifier
  - popd
  - mv src/sourceforts-server-build-notification-handler.zip .
  - docker run -v $(pwd):/tmp -w /tmp -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY garland/aws-cli-docker aws s3 cp sourceforts-server-build-notification-handler.zip s3://$AWS_S3_BUCKET/sourceforts-server-build-notification-handler.zip

after_success:
  - ./.travisci/send.sh success $DISCORD_WEBHOOK_URL
after_failure:
  - ./.travisci/send.sh failure $DISCORD_WEBHOOK_URL
